apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: linkding
    linkding/instance: {{ .Release.Name }}
    app.kubernetes.io/name: linkding
    app.kubernetes.io/version: "1.38"
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: dojo-suite
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    linkding/instance: {{.Release.Name}}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
