apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-runner-dojo-secret
  namespace: gitlab-runner
spec:
  encryptedData:
    runner-token: AgBI9nHBQTXR9+eskY77awXzZhcAgewPd3rJ5MWwahjwAYPnZU44qCjuP7jR+V75wENygfLPzZmYzi8r+EMN/iSN/OrpHB7ZiaaBhMMR8lNUQ0SwfldL2C3mLajH01Bsb/daCNqQDufMSRk4vbpw7II1aFvue+wS3Kl7X1Ag/1raW2IWXO+oDSU0H2M+DwQbdts0A3olhzHsV9yBQ7p7v81EWMOlVLRp1SqMEZBmBVZpnXdygA695Un1KAG8RAEbkFS++F0jUDwchtQLEdEajlo7aKC0+tuqtHiTuvblQzdWqJuj8T2Oo92QSVflSxijfhuNbUgHNwaC4MihpnfogSTwFyxq/BUD08Im9L3PkYNmCv8dgSW9ywPX+zmF1f5LCsZDlSKhOSO0MbG1E7pIWc2prkHOdkka96GbEktDhsKQ+2Wa8fLabJ/MVvpX3bqP3iu7iyaJNVi1UpCgK4EHUQ+g5LvVe1mzXuxuwGB0VH46SlD/zgf6TVbNqYvPZrmsOZct/mWmtITfaZhZ4fCCNeitCtPFNW1YYi2H3uahgpfAJmpbjBt2u622Rdhg3JHVn7hHLDyDVtskTLYFIjY+vJszLrAKIugjCnDdrOaOFxBShTlWz5Ei5HNpS8QQ7Dv7RhEqUq57Gan245LRjn03FlV2nRNAE7Zva66rT/V+69vIHnzVcQjyrk9TOW+W1H3zS8ume4+OFtKNcwmi2hsU1KB0aNwZnAFcgLTy41nt
  template:
    metadata:
      name: gitlab-runner-dojo-secret
      namespace: gitlab-runner
    type: Opaque
