apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: troubleshooting-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: troubleshooting-shell
  template:
    metadata:
      labels:
        app: troubleshooting-shell
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sh", "-c", "while true; do sleep 3600; done"]
