apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
    keycloak/instance: {{ .Release.Name }}
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/version: "26.1.3"
    app.kubernetes.io/component: IAM
    app.kubernetes.io/part-of: dojo-suite
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      keycloak/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: keycloak
        keycloak/instance: {{ .Release.Name }}
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/version: "26.1.3"
        app.kubernetes.io/component: IAM
        app.kubernetes.io/part-of: dojo-suite
        app.kubernetes.io/managed-by: argocd
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.1.3
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
            - name: KC_HEALTH_ENABLED
              value: "true"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 9000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
              scheme: HTTP
