apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: keycloak
    keycloak/instance: {{ .Release.Name }}
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/version: "26.1.3"
    app.kubernetes.io/component: IAM
    app.kubernetes.io/part-of: dojo-suite
    app.kubernetes.io/managed-by: argocd
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    keycloak/instance: {{ .Release.Name }}
