apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mosquitto-replicaset
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      dojo/app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
        dojo/app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        ports:
        - containerPort: 1883
        - containerPort: 9001
