apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mosquitto-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      hass/app: mosquitto
  template:
    metadata:
      generateName: mosquitto-pod-
      labels:
        app: mosquitto
        hass/app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto
          ports:
            - containerPort: 1883
            - containerPort: 9001
