apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: infisical-{{.Release.Name}}-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: infisical-dojo-{{.Release.Name}}-store
  target:
    name: {{.Release.Name}}-env
  dataFrom:
    - find:
        name:
          regexp: .*
