apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: infisical-{{.Release.Name}}-store
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            name: infisical-universal-auth-credentials
          clientSecret:
            key: clientSecret
            name: infisical-universal-auth-credentials
      secretsScope:
        projectSlug: dojo-u3qf
        environmentSlug: lab
        secretsPath: /{{.Release.Name}}
        recursive: true
