apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
spec:
  selector:
    hass/app: mosquitto
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: mqttws
      protocol: TCP
      port: 9001
      targetPort: 9001
