apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: infisical-fetch-all-secrets-example
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-dojo
  target:
    name: auth-api-cluster
  dataFrom:
    - find:
        name:
          regexp: .*
