apiVersion: v1
kind: Secret
metadata:
  name: infisical-universal-auth-credentials
  namespace: external-secrets
type: Opaque
stringData:
  clientId: <machine identity client id>
  clientSecret: <machine identity client secret>
