apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-deploy
  labels:
    app: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      dojo/app: transfer
  template:
    metadata:
      labels:
        app: httpbin
        dojo/app: transfer
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80
