apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: transfer-rs
spec:
  replicas: 4
  selector:
    matchLabels:
      dojo/app: transfer
  template:
    metadata:
      labels:
        app: transfer
        dojo/app: transfer
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80
