---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkding
  namespace: argocd
spec:
  project: dojo
  source:
    repoURL: https://github.com/downbot/dojo.cd.git
    path: app/linkding
    targetRevision: HEAD
    helm:
      parameters:
        - name: hostname
          value: bm.${DOMAIN}
  destination:
    namespace: linkding
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
