---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto
  namespace: argocd
spec:
  project: hass
  source:
    repoURL: https://github.com/downbot/dojo.cd.git
    path: app/mosquitto
    targetRevision: HEAD
  destination:
    namespace: home-assistant
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
