apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transfer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/downbot/dojo.cd.git
    path: app/transfer
    targetRevision: HEAD
    helm:
      parameters:
        - name: hostname
          value: transfer.example.com
  destination:
    namespace: transfer
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
