apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transfer
spec:
  project: dojo
  source:
    repoURL: https://github.com/downbot/dojo.cd.git
    path: transfer
    targetRevision: HEAD
  destination:
    namespace: transfer
    name: dojo
