---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: "{{.Release.Name}}"
  labels:
    app: transfer
    transfer/instance: "{{.Release.Name}}"
    app.kubernetes.io/name: transfer
    app.kubernetes.io/version: "1.5"
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: dojo-suite
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      transfer/instance: "{{.Release.Name}}"
  template:
    metadata:
      labels:
        app: transfer
        transfer/instance: "{{.Release.Name}}"
        app.kubernetes.io/name: transfer
        app.kubernetes.io/version: "1.5"
        app.kubernetes.io/component: webserver
        app.kubernetes.io/part-of: dojo-suite
        app.kubernetes.io/managed-by: argocd
    spec:
      containers:
        - name: transfer
          image: ghcr.io/downbot/uploadsh:v1.5
          envFrom:
            - configMapRef:
                name: "{{.Release.Name}}-config"
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: uploads
              mountPath: /usr/src/app/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: "{{.Release.Name}}-files-pvc"
