---
apiVersion: v1
kind: Service
metadata:
  name: "{{.Release.Name}}-service"
  labels:
    app: transfer
    transfer/instance: "{{.Release.Name}}"
    app.kubernetes.io/name: transfer
    app.kubernetes.io/version: "1.5"
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: dojo-suite
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    transfer/instance: "{{.Release.Name}}"
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
