apiVersion: v1
kind: Secret
metadata:
  name: argocd-dojo-cluster-config
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: dojo
  server: https://kubernetes.default.svc
  config: |
    {
      "tlsClientConfig": {"insecure":false}
    }

