---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dojo-cluster
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: linkding
            namespace: linkding
            hostname: bm.zulu.ar
          - name: transfer
            namespace: transfer
            hostname: up.zulu.ar
  template:
    metadata:
      name: '{{name}}-cloud'
    spec:
      project: default
      destination:
        namespace: '{{namespace}}'
        server: https://kubernetes.default.svc
      source:
        path: 'app/{{name}}'
        repoURL: https://github.com/downbot/dojo.cd.git
        targetRevision: HEAD
        helm:
          parameters:
            - name: hostname
              value: '{{hostname}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
...
