---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dojo
  namespace: argocd
spec:
  description: "Dojo Cluster Project"
  sourceRepos:
    - https://github.com/downbot/dojo.cd.git
  destinations:
    - name: dojo
      namespace: '*'
      server: https://kubernetes.default.svc
