---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hass
  namespace: argocd
spec:
  description: "Home Assistant"
  sourceRepos:
    - https://github.com/downbot/dojo.cd.git
  destinations:
    - name: dojo
      namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
